### ISSUE TITLE
Header is not populated correctly in eventlog mode

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#1]
It is currently left empty as not quite the same information is available as the heap profile.

**Comment by mpickering** [comment]
Partially fixed but need to work out what the timestamps in the event log actually mean

**Comment by BinderDavid** [comment]
Related to #15 
I'm currently getting errors trying to read from the Header:

```
eventlog2html: Header begin marker not found
CallStack (from -prof):
  GHC.RTS.Events.Incremental.readHeader (src/GHC/RTS/Events/Incremental.hs:(107,1)-(119,43))
  GHC.RTS.Events.Incremental.readEventLog (src/GHC/RTS/Events/Incremental.hs:(151,1)-(154,64))
  GHC.RTS.Events.readEventLogFromFile (src/GHC/RTS/Events.hs:103:1-72)
  Events.chunk (src/Events.hs:23:1-67)
  Data.generateJson (src/Data.hs:(20,1)-(33,51))
  Main.doHtml (main/Main.hs:(64,1)-(70,15))
  Main.argsToOutput (main/Main.hs:(29,1)-(32,28))
  Main.main (main/Main.hs:(23,1)-(26,16))
```

**Comment by mpickering** [comment]
@BinderDavid Have you setup git LFS? You might not have downloaded the eventlog?

Which one are you trying it on?

**Comment by BinderDavid** [comment]
Ah sorry, I discovered it myself. I didn't check that you removed the old ghc.eventlog.

It's the generic error if you try to read a non-existing file.

**Comment by mpickering** [comment]
I moved it into the `docs/examples` subdirectory. Along with a bigger eventlog (89M!) from profiling `haskell-ide-engine`.

**Comment by mpickering** [comment]
I think this is fixed now. We display the time + arguments.
