### ISSUE TITLE
Tooltip: Display name of band which is currently being hovered over

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#12]
Relies on #11 perhaps

**Comment by mpickering** [comment]
I started looking into this. It looks harder than I thought.

**Comment by mpickering** [comment]
The idea is that 

1. Make the name of the trace to each verticle trace marker by using `layer` with a `text` layer. (https://vega.github.io/vega-lite/examples/layer_bar_labels.html)
2. Conditionally display the text depending on which traces is selected.
3. Make the tooltip just show the type of allocation rather than anything to do with the trace.

**Comment by BinderDavid** [comment]
I also spent a lot of time trying to find a way, looking through the Vega and VegaLite specs for a solution. The simplest solution, I think, is generating the necessary information on the Haskell side.

The "samples" field in the JSON currently looks like this:

```
  {
    "k": 0,
    "x": 7.687447468,
    "c": "OTHER",
    "y": 0
  },
  {
    "k": 0,
    "x": 7.896682800000001,
    "c": "OTHER",
    "y": 0
  },
  {
    "k": 0,
    "x": 8.086312533000001,
    "c": "OTHER",
    "y": 0
  },
  {
    "k": 0,
    "x": 8.283588356000001,
    "c": "OTHER",
    "y": 0
  },
  {
    "k": 0,
    "x": 8.453890633,
    "c": "OTHER",
    "y": 0
  }
]
```
Each entry could have additional "desc" and "descTime" fields, which contains the name of the closest previous Trace.

The tracesLayer would then be purely for generating the vertical bars, and tooltips could be generated from  the bandsLayer.

**Comment by mpickering** [comment]
https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIK7k6MEnS68YWIm4B3RkupgXyRtXxhuADMbO1gAql0wI1RkOjUNSDdNFmwwaQAGdNVcHz88VIAmTPUISDF0AE9kXVSAbVAIUs10PEwcYEhWXTFUyGbW0lYlNEIxbgqYpTwRdHhdblhYEXdNVlg8fR15RRUAXxLGyAxdAGteuyt4xqhkJXhuTXdqVIbrqAAPF403yGjkAFUlMxelU7KhlClspBAoxkGJNL1+sg1FA8BVCMjTHgRtxdOgegc3lB0O9GLAXtDcRh8qYAKQATUgu2+EH2LNKFS+ROJ1Gollo2N6sFYqBR0Nh8N69yG+ShaIxvQAjqx0FNmC1GFRIOy2UTIPcxjV2uzDjC4QjTLBqrDyYSfvLMVAlNxUO58VduZAEPjHR1+GhHfqWjRcRUiuwmSbmdddvswMAmi02vHIBR8awdNh6n1g70iukAOwidIADmLAEYACqFrCZWvpOiZdIALTF2gQ53Y8CZAF1o40obd7o8PBTPu1xebEbmTdyB6jGDFAcDTKDdOCpohtXO53L0YHsahCLj3bOd2e57G7aVylUjWBs8czqZdKwxMjdY1XqUnxSHb1sXefIL3nYkJGoEwymQQJgJ3ec+nHNIQIgKFNE5HARAATgAVmQsAoXYdArQkYYAO4QhtzgsBdjADRBzuB4nheWi9UAmkUzNSVTHbbs9wVUxnVdJRTyoxp+znPCYxZfsNA0PsexAZkgA

This is what I have in mind. Then making the display of the label conditional on if the trace is selected or not and change the tooltip to just display information about the bands.

I won't return to this until this evening.

**Comment by mpickering** [comment]
I'm going to keep working on this now.

**Comment by BinderDavid** [comment]
I have something that works on my branch improve-tooltips. I had a conceptual misunderstanding about how tooltips work. I thought that only one layer can provide the tooltips, and that this layer has to have all the data available to produce the tooltips. Now that I understand how vegalite computes the tooltips this has become much simpler.

**Comment by mpickering** [comment]
Oh? I perhaps misunderstood this as well. Let me try what you have done.

**Comment by BinderDavid** [comment]
The simplest way to get nicer labels for the tooltips is to change the fieldnames of the generated JSON file.
E.g.
"x" -> "time"
"tx" -> "time"
"desc" -> "event"
"c" -> "type"

**Comment by mpickering** [comment]
It is not documented but you can use "title" to set the tooltip label. I would prefer to do this as the I hate that the implementation detail leaks out.

**Comment by mpickering** [comment]
[Example](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATZAgBOjQnh4qckAIJhYjVITHIw7dLrBIneMAHdmiMGnbJNbU0wTXQ8dE9vMDxubjEjQjo1DUhQ8OwwUAgISAp0MVYdDIBtDWzMyExTMzUodgyAJgAOAF91cohgSozIACFayHqcAFZhtrLsrqqoAGEBobAAFmlxjorpyAAReYyATgBGVY6pnoBRHZwmw-bj7tMAMQuwYZWb8pPTAHEn-d2j97uUAAEk8mgB2f6TQGQACST2GDRaEwAuhojpAMLoANY9Ry6ZI5ZBKeDcTSMJTUDJZbKQAAeVMgADNGMgxJoephVFA8ABPQjIHrcXRkpT5SCQyA8hnM1ns0z1LmQXn8noAR1Y6CURnCRio4re3Ni8QMJS6MrZuIGyoFpnVmu1YUYesV2rsPXg+omZpZFtMnO5fJtUCU3FQ5LFLuYbtM7JaqIgSJaQA)

**Comment by BinderDavid** [comment]
Ok, that makes it much simpler. I thought about computing new fields with the appropriate names, but that would be a lot of senseless computation just for changing some labels...

**Comment by BinderDavid** [comment]
"format" also works on tooltips. So we can truncate the time with e.g. ".3f"

**Comment by mpickering** [comment]
I think the allowed things are similar to field definitions (https://vega.github.io/vega-lite/docs/encoding.html#field-def)

Let's go with the approach on your branch for now. I would prefer if the traces tooltip just had the label name rather than the time. It will make it more compact and you can read the time from the axis.

**Comment by BinderDavid** [comment]
Ok, I'll prepare a pull request.
