### ISSUE TITLE
Hovering near a grey line doesn't work anymore

### ISSUE THREAD

**Issue by adinapoli** [mpickering/eventlog2html#127]
Howdy @mpickering ! 

I hope you are well 😉 I have noticed something bizarre: it seems like using `traceMarker` in the latest version of `eventlog2html` does produce a grey line, but the latter doesn't have any label attached, greatly reducing the usefulness of the feature.

At first I thought it was my browser, or that I was doing something idiotic, but if I compare the chart [here](https://mpickering.github.io/eventlog2html/) with a Wayback machine snapshot around July 2019, the latter works:

https://web.archive.org/web/20190626105133/https://mpickering.github.io/eventlog2html/

Therefore, this seems to suggest a regression in the generated chart. Am I missing something obvious here?

**Comment by mpickering** [comment]
It seems like I broke this during on the of updates.

**Comment by adinapoli** [comment]
I have downgraded to `0.6.0.0` and this version exhibit the right behaviour. I don't know if that helps, but it's surely a tangible starting point for a `git bisect`.

**Comment by mpickering** [comment]
Fixed in master.
