### ISSUE TITLE
Make it easy to switch between different area graph stack types

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#13]
There are three different stack types. There should be buttons to switch between all three.

https://github.com/vega/vega-lite/issues/3338

Related to #9 because we don't want to embed the data multiple times. Duplicating the specifications is ok though.

**Comment by BinderDavid** [comment]
I implemented this by storing the JSON data in Toplevel Javascript variables and generating multiple Vegalite Specs, using Javascript to select which spec to show to the user.

**Comment by mpickering** [comment]
Fixed in #39
