### ISSUE TITLE
Resolve discrepancy between vega-lite versions

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#14]
It seems that `hvega` generates vega-lite 2 but the rendering library we are using is vega-lite 3. 
Ideally `hvega` just generates vega-lite 3.

**Comment by BinderDavid** [comment]
Created a pull request to fix this upstream:

https://github.com/DougBurke/hvega/pull/19

**Comment by BinderDavid** [comment]
The fix is now upstream in v 0.3  of hvega: http://hackage.haskell.org/package/hvega-0.3.0.0/changelog
