### ISSUE TITLE
Profiles based on .hp files are incorrect.

### ISSUE THREAD

**Issue by AndreasPK** [mpickering/eventlog2html#141]
The memory useage reported by the profile when based on the .hp file for GHC-Head seems to be wildly inaccurate.

![image](https://user-images.githubusercontent.com/5500646/110795190-de2a5480-8276-11eb-9dca-9cd522c82214.png)
![image](https://user-images.githubusercontent.com/5500646/110795142-cf43a200-8276-11eb-8487-8b66b0bbf9de.png)

This is for version eventlog2html-0.8.3

**Comment by mpickering** [comment]
This is probably an issue with the .hp file rather than eventlog2html. Using the eventlog is usually much more robust.
