### ISSUE TITLE
Cost centers not shown in detailed view

### ISSUE THREAD

**Issue by pepeiborra** [mpickering/eventlog2html#145]
I'm looking at a cost centre profile (`-hc`) rendered with the default options using version 0.9.0. The label column in the detailed view contains only integers,  how can I map those integers to actual cost centres? 
<img width="1792" alt="Screenshot 2021-06-20 at 12 04 58" src="https://user-images.githubusercontent.com/26626/122671684-c50f3900-d1bf-11eb-8ae0-c87fb3a6e0e6.png">

**Comment by mpickering** [comment]
I am never normally using cost centre profiling so I didn't consider this case. You can see the top 15 cost centres in the "cost centre" tab but there's no way currently to see information about each cost centre band (just because I didn't implement it).

**Comment by pepeiborra** [comment]
What would it take to implement it?
