### ISSUE TITLE
Add "normalised line chart"

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#18]
The normalised line chart normalises each data series relative to its maximum value. This 
makes it easy to identify leaking elements as they will increase throughout the execution of
the program.

I have implemented this on a branch.

https://github.com/mpickering/hp2pretty/tree/normalised-line-chart

**Comment by BinderDavid** [comment]
See also #20 
Should we choose different visualizations on the command line or in the generated HTML file?
