### ISSUE TITLE
Incompatibilty with blaze-html >= 0.9.2.0

### ISSUE THREAD

**Issue by maralorn** [mpickering/eventlog2html#186]
Unfortunately `blaze-html` started importing a conflicting `template` function. (see [Changelog](https://hackage.haskell.org/package/blaze-html-0.9.2.0/changelog)).

```
[19 of 19] Compiling Eventlog.HtmlTemplate ( src/Eventlog/HtmlTemplate.hs, dist/build/Eventlog/HtmlTemplate.o, dist/build/Eventlog/HtmlTemplate.dyn_o )

src/Eventlog/HtmlTemplate.hs:214:16: error:
    Ambiguous occurrence ‘template’
    It could refer to
       either ‘H.template’,
              imported from ‘Text.Blaze.Html5’ at src/Eventlog/HtmlTemplate.hs:14:1-39
           or ‘Eventlog.HtmlTemplate.template’,
              defined at src/Eventlog/HtmlTemplate.hs:137:1
    |
214 |   renderHtml $ template x as $ allTabs x as
    |                ^^^^^^^^
```
[Source of build error](https://hydra.nixos.org/build/253351290/nixlog/1/tail)

**Comment by BinderDavid** [comment]
Thanks for the report :) I already changed the metadata on Hackage and put an upper bound of `< 0.9.2` in place. As soon as CI is green I will also merge the proper fix into the codebase.

**Comment by mpilgrem** [comment]
@BinderDavid, is there a plan to release a version with the proper fix on Hackage?

**Comment by BinderDavid** [comment]
@mpilgrem I am preparing a release in https://github.com/mpickering/eventlog2html/pull/190 
After the PR is merged I add a new git tag and release on Hackage :)
