### ISSUE TITLE
Select  visualisation on commandline or in HTML

### ISSUE THREAD

**Issue by BinderDavid** [mpickering/eventlog2html#20]
Since we now generate HTML with Javascript and not SVGs, there are two different ways we can select different visualizations:

- Select them as an option on the command line and generate only that specific visualization
- Generate the HTML with some Javascript for selecting a specific visualization style.

The second option has the advantage that person A can generate a self-contained HTML file and send it to person B who can choose how to inspect the data. The disadvantage is that we have to write additional Javascript.

**Comment by mpickering** [comment]
I think that we should try option B. All the javascript will do is remove the contents of a `div` and execute the `vegaEmbed` command again.

**Comment by BinderDavid** [comment]
Ok, I also thought that this would be the preferred option. This would mean that we can remove most of the commandline options in the parser.
