### ISSUE TITLE
Investigate old `--uniform-scale` option

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#24]
I don't know what the `--uniform-scale` option is supposed to do, it made no difference on my test `.hp` file. The scales look quite uniform to me by default anyway. 

When we work out what it's for then we need to decide whether it's worth supporting in the html frontend.

**Comment by BinderDavid** [comment]
The uniform-scale option was used in the old Main file. I think it is only used when you process multiple files. In that case, it creates several svgs which use the same scale (for time and/or memory) across all generated svgs.

**Comment by BinderDavid** [comment]
If we don't need this feature, I can remove it and close this issue together with #27

**Comment by mpickering** [comment]
Ah, well we still do support generating multiple files but it would probably be hard to implement? I doubt anyone will miss this feature too much.
