### ISSUE TITLE
Make the size of the chart configurable by a parameter

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#37]
This is useful if you want to embed a chart into another webpage.

We should allow a user to specify a width/heigh and scale the other charts based on this number.

**Comment by BinderDavid** [comment]
How is the workflow "Embed a chart into another website" supposed to work? Do you mean extracting an SVG/PNG, or the ability to embed an interactive chart?

**Comment by mpickering** [comment]
The ability to embed an interactive chart. I have implemented this on the documentation branch so we can embed real examples into the documentation.
