### ISSUE TITLE
Is the 0.1 release ready?

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#64]
Is there anything left outstanding to do before the 0.1 release? I would like to upload the package tonight. 

Do I need to write a separate blog post announcing the project or is the documentation page sufficient?

**Comment by BinderDavid** [comment]
I still get a number of warnings when I do a fresh compile. We could either fix them all (mostly unused imports/bindings + name shadowing). Then we could publish with no warnings when -Wall is enabled.

**Comment by mpickering** [comment]
Yes that's a good point. We need to fix that. I have sent the project to some GHC developers to get their feedback if there is anything missing from the documentation.

**Comment by BinderDavid** [comment]
I am currently fixing the warnings.
There have also been upstream changes in hvega which we can use in a future release. (Not published to Hackage yet).

**Comment by BinderDavid** [comment]
Fixed warnings in #65

**Comment by mpickering** [comment]
I will do the release after #69 is merged.

**Comment by BinderDavid** [comment]
Great! :champagne: 

I will be on the train for the next 2h and not respond before ~24:00. So you have to do any pull-requests yourself until then.

**Comment by mpickering** [comment]
Released. Thanks for all your work @BinderDavid. Without you, the release wouldn't have been nearly as good or happened so soon!
