### ISSUE TITLE
Rewrite documentation

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#7]
The documentation is not very relevant any more. We should rewrite it from scratch.

**Comment by mpickering** [comment]
I made a good start on a landing page for the project which will be able to display sample heap profiles. It will be built using the CI and deployed to github pages so it is accessible at `mpickering.github.io/eventlog2html`.

https://github.com/mpickering/eventlog2html/tree/documentation

**Comment by mpickering** [comment]
Need to update README and complete the examples page. 

The documentation site is looking good I think. 

https://mpickering.github.io/eventlog2html

**Comment by mpickering** [comment]
@BinderDavid Do you think anything is obviously missing from the documentation site? 

https://mpickering.github.io/eventlog2html

**Comment by BinderDavid** [comment]
Maybe a FAQ section? 2 questions I can think of right now:

- Q: How to work offline. A: --include-json
- Q: Does eventlog2pretty support .hp files? A: As long as eventlog profiling does not support all features, there is a compatibility option to parse .hp files.

**Comment by mpickering** [comment]
I added about `--json`, `--include-js` and `--heap-profile`.
