### ISSUE TITLE
Provide option for filename of output.

### ISSUE THREAD

**Issue by BinderDavid** [mpickering/eventlog2html#70]
There is currently no commandline option to specify the name of the outputfile. This is useful for comparing multiple eventlog versions of one program without overwriting previous versions.

Proposed behaviour of implementation:
```
eventlog2html -o mypage.html file.eventlog
```
produces html file `mypage.html`

```
eventlog2html -o myjson.json --json file.eventlog
```
produces json file `myjson.json`

The argument to `-o` is not used to determine the type of the output.
The `-o` option can only be used with one eventlog file as input.

I will implement this feature if the above described behaviour is ok.

**Comment by mpickering** [comment]
Sounds good to me.
