### ISSUE TITLE
Move to new version of hvega

### ISSUE THREAD

**Issue by BinderDavid** [mpickering/eventlog2html#72]
There is currently a lot of activity for implementing v3 of the vegalite spec in hvega, see: https://github.com/DougBurke/hvega/pull/29

Switching to the newer version will enable us to get rid of most, hopefully all,  workarounds currently in VegaTemplate.

This will also resolve #14

**Comment by DougBurke** [comment]
Note that #14 should already be fixed, as [version 0.3 is on hackage](http://hackage.haskell.org/package/hvega).

**Comment by BinderDavid** [comment]
Ah, thank you. So for that we just have to bump the hvega version in the cabal file.
