### ISSUE TITLE
eventlog2html.exe: foo.eventlog.html: commitBuffer: invalid argument (invalid character)

### ISSUE THREAD

**Issue by spacekitteh** [mpickering/eventlog2html#73]
As per the title.

It produces a HTML file with only 3 scripts in the header.

Running on Windows 10, 64bit.

**Comment by mpickering** [comment]
Please provide instructions about how to reproduce the issue.

**Comment by BinderDavid** [comment]
Thanks for the bug report.

Could you do the following things which would help us close in on the error?
- Do you use eventlogs or heap profiles (.hp files) ?
- If you use eventlogs, do you add traces with Debug.Trace.traceEvent?
- Does the error appear if you use the "--json" option to output a json file?
- What ghc options (relating to profiling) do you use when generating the executable?
- What RTS options do you use for generating the eventlog/heap profile?

**Comment by mpickering** [comment]
It looks to me this bug might just be trying to run `eventlog2html` on a `html` file rather than an eventlog.

**Comment by spacekitteh** [comment]
```powershell
> stack build --ghc-options "-debug" --no-library-stripping --no-executable-stripping
...
> .\cultural-evolution-exe.exe +RTS -r -l
...
> eventlog2html .\cultural-evolution-exe.eventlog
eventlog2html.exe: .\cultural-evolution-exe.eventlog.html: commitBuffer: invalid argument (invalid character)
```
Running with the `--json` option produces the following file, with no errors:

```json
{"traces":[],"samples":[{"k":0,"x":7.7220000000000006e-3,"c":"OTHER","y":0},{"k":0,"x":120.1432723,"c":"OTHER","y":0}]}
```

The original `.eventlog` file is nearly 60MB, so that doesn't seem like appropriate output at all. I don't use any extra tracing.

**Comment by mpickering** [comment]
The retainer profiler does not output events yet to the eventlog. You should use the `-p` flag with the `.hp` file.

**Comment by mpickering** [comment]
We should make sure it doesn't error though when passed an empty file.

**Comment by mpickering** [comment]
This should be fixed now in master.
