### ISSUE TITLE
Rename and move repo

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#8]
The project shares almost code now with the original `hp2pretty` library apart from the code which parses `.hp` files and the command line parsing. The eventlog parsing and rendering code is all new. 

Therefore it makes most sense if we rename the program so there's not any confusion about the tools. 

Perhaps the name should mention the eventlog and heaps. Perhaps `eventlog2html` is a good name which fits into the existing naming schemes. That way, everyone will know that it's a heap profiling tool and gives us scope to extend the visualisations to other
eventlog events in future.

**Comment by BinderDavid** [comment]
For naming alternatives there are also Heapscope and Threadscope which do similar things:

- https://github.com/kfish/heapscope
- http://hackage.haskell.org/package/threadscope

Using this naming scheme, "Eventscope" would be a possibility.

**Comment by mpickering** [comment]
I am quite a fan of `eventlog2html` as to me it is immediately clear what this program does, if you know what `hp2ps` or `hp2pretty` or `hp2any` do.

**Comment by BinderDavid** [comment]
Ok, then eventlog2html it is :+1:

**Comment by mpickering** [comment]
I think this is done.
