### ISSUE TITLE
Isolating individual traces is very slow

### ISSUE THREAD

**Issue by jberryman** [mpickering/eventlog2html#81]
It takes ~ 10 seconds for the change to appear for me on firefox.

**Comment by mpickering** [comment]
What do you mean exactly? How do I reproduce it?

**Comment by jberryman** [comment]
Click on one of the colored little "o"s in the legend :

![legend](https://user-images.githubusercontent.com/210815/62097144-f55c3000-b253-11e9-98cf-15249e2423d1.png)

I don't have much experience with these JS libraries but whatever the EKG console uses seems pretty snappy with 10s of thousands of data points and some amount of realtime updates, if you're looking for a replacement

**Comment by mpickering** [comment]
OK -- we are using a high-level javascript library so don't have much control over the rendering time. Is this a very big eventlog? I just tried on one with 2800 samples and it was responsive (<1 second).

**Comment by jberryman** [comment]
I don't quite remember, sorry. It may have been a big eventlog, but I wasn't trying to stress eventlog2html, i.e. whatever I was doing seemed like a normal thing I'd be using eventlog2html for. 

I should be working with it more in coming months, and will try to provide improvements/better info then!

**Comment by mpickering** [comment]
I haven't observed any significant slowness with any reasonably sized profile. Please open another issue if you have a way to reproduce a significant slow down.
