### ISSUE TITLE
Check what version of GHC an eventlog was generated with

### ISSUE THREAD

**Issue by mpickering** [mpickering/eventlog2html#83]
Eventlogs from `ghc-8.4.4` don't contain the profiling events and lead to an empty eventlog. 
Is it possible to gather the version of GHC from the eventlog?

**Comment by BinderDavid** [comment]
The eventlog I tested did not contain the "Version" event of http://hackage.haskell.org/package/ghc-events-0.9.1/docs/GHC-RTS-Events.html , if this is indeed the correct event.

**Comment by mpickering** [comment]
```
[matt@nixos:~/hp2pretty]$ ghc-events show eventlog2html.eventlog | grep version
29: RTS name and version (size variable)
74297: capset 0: RTS version "GHC-8.6.5 rts_p"
26101498: cost centre 1622 CAF in GHC.Float.ConversionUtils at <entire-module> CAF
26435897: cost centre 1168 time_hi_and_version in Data.UUID.Types.Internal at Data/UUID/Types/Internal.hs:115:9-27
26589000: cost centre 909 version in GHC.RTS.EventTypes at src/GHC/RTS/EventTypes.hs:291:26-32
```

**Comment by mpickering** [comment]
It is in the `RtsIdentifier` event

**Comment by mpickering** [comment]
WIP branch https://github.com/mpickering/eventlog2html/tree/wip/parse-version
